#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
spring:
  cloud:
    gateway:
      routes:
#        - id: test
#          uri: https://google.com
#          predicates:
#            - Query=url,google
#        - id: qq
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq

        - id: product_route
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://members
          predicates:
            - Path=/api/members/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: warehouse
          uri: lb://warehouse
          predicates:
            - Path=/api/warehouse/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

