spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: https://google.com
          predicates:
            - Query=url,google
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

